# Estructura de control

Descripció:
- Comencem a familiaritzar-nos amb les estructures de control de Python

## NIVELL 1
   

### Exercici 1
L'exercici consisteix a crear un programa que et classifiqui una variable numèrica en funció de l’escala Suspès/Aprovat/Notable/Excel·lent.



In [10]:
import numpy as np

contador = 0
x= -1

#he intentat fer una espècies de do while de java perquè la x es vagi repetint en bucle fins a entrar el número correcte
while x<0 or x>10:
    x= float(input("Entra una nota entre el 0 i el 10 "))
    contador =+ contador
    if x >= 0 and x<=10:
        print("La nota introduïda és un", x, "i correspon a:")
        break

if x >=0 and x<5:
    print("Suspès")
elif x >=5 and x<7:
    print("Aprovat")
elif x >=7 and x<9:
    print("Notable")
elif x >=9 and x<=10:
    print("Excel·lent")


Entra una nota entre el 0 i el 10 7
La nota introduïda és un 7.0 i correspon a:
Notable


### Exercici 2
Utilitzant el següent tutorial Programiz: Python Input, Output and Import crea un programa que et pregunti dos números. T’ha de mostrar un missatge dient si el primer és més gran, el segon és més gran o són iguals.



In [11]:
x=float(input("Escriu un número "))
y=float(input("Escriu un altre número "))

if x < y:
    print("El número", x, " és més petit que el número", y)
elif x > y:
    print("El número", y, " és més petit que el número", x)
elif x == y:
    print(x, "i", y, "són iguals")


Escriu un número 6
Escriu un altre número 5
El número 5.0  és més petit que el número 6.0


### Exercici 3
Crea un programa que et pregunti el teu nom, i et demani un número. Si el número és 0, hauria de mostrar un missatge d’error. En cas contrari, hauria de mostrar el nom repetit tants cops com indiqui el número. Per exemple, “Joan Joan Joan”.



In [12]:
nom = input("Escriu el teu nom ")
contador = 0
x= 0

#he intentat fer una espècies de do while de java perquè la x es vagi repetint en bucle fins a entrar el número correcte
while x<=0:
    x= int(input("Escriu un número positiu enter "))
    contador =+ contador
    if x > 0:
        print("El número que has triat és el", x)
        break
nomE = nom + " "
print(nomE*x)

Escriu el teu nom Anna
Escriu un número positiu enter 6
El número que has triat és el 6
Anna Anna Anna Anna Anna Anna 


### Exercici 4
Crea un programa que donada una llista qualsevol, et digui si es simètrica o no. Si ho és, que et digui quants elements té.


In [13]:
llista = np.random.randint(100, size=(10))
llistaRev = llista[::-1]     #amb numpy hem de fer servir [::-1] per fer l'acció de reverse() normal de python
#llistaRev = llista

#comentar una de les dues llistaRev anteriors per saber que funciona l'if else següent quan hi ha  o no simetria

print(llista)
print(llistaRev)

if np.array_equal(llista, llistaRev):
    print("La llista és simètrica i té ", len(llista), "elements")
else:
    print("La llista no és simètrica")


[ 6 10 23 99 68 54 57 68 31  7]
[ 7 31 68 57 54 68 99 23 10  6]
La llista no és simètrica


### Exercici 5
Crea un programa que donada una llista, et digui quants números coincideixen amb la seva posició. Per exemple [3,4,2,0,2,3,6] el 2 i el 6 coincideixen.

In [8]:
llista = np.random.randint(10, size=(10))
#llista = [0,3,2,4,3,5,9,7,5,2]
print(llista)

contador = 0
valorPosicio = 0


for valorPosicio in range(0,len(llista)):
    #if str(valorPosicio) == llista[valorPosicio]:
    if np.array_equal(str(valorPosicio), llista[valorPosicio]):
        contador += contador
       
print("Concideixen en número i posició un total de", contador, "elements")



[5 5 4 0 6 3 1 5 4 9]
Concideixen en número i posició un total de 0 elements
